
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const AIAssistant = lazy(() => import("./pages/AIAssistant.tsx"));
const AnalyticsManager = lazy(() => import("./pages/AnalyticsManager.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const CRMManager = lazy(() => import("./pages/CRMManager.tsx"));
const CalendarManager = lazy(() => import("./pages/CalendarManager.tsx"));
const ChatManager = lazy(() => import("./pages/ChatManager.tsx"));
const Clientes = lazy(() => import("./pages/Clientes.tsx"));
const Configuracion = lazy(() => import("./pages/Configuracion.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const DatabaseManager = lazy(() => import("./pages/DatabaseManager.tsx"));
const IntegrationHub = lazy(() => import("./pages/IntegrationHub.tsx"));
const InventoryManager = lazy(() => import("./pages/InventoryManager.tsx"));
const NuevaRenta = lazy(() => import("./pages/NuevaRenta.tsx"));
const Rentas = lazy(() => import("./pages/Rentas.tsx"));
const Reportes = lazy(() => import("./pages/Reportes.tsx"));
const ShopifyManager = lazy(() => import("./pages/ShopifyManager.tsx"));
const StripeManager = lazy(() => import("./pages/StripeManager.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/ai-assistant", element: <UserGuard><AIAssistant /></UserGuard>},
	{ path: "/aiassistant", element: <UserGuard><AIAssistant /></UserGuard>},
	{ path: "/analytics-manager", element: <UserGuard><AnalyticsManager /></UserGuard>},
	{ path: "/analyticsmanager", element: <UserGuard><AnalyticsManager /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/crm-manager", element: <UserGuard><CRMManager /></UserGuard>},
	{ path: "/crmmanager", element: <UserGuard><CRMManager /></UserGuard>},
	{ path: "/calendar-manager", element: <UserGuard><CalendarManager /></UserGuard>},
	{ path: "/calendarmanager", element: <UserGuard><CalendarManager /></UserGuard>},
	{ path: "/chat-manager", element: <UserGuard><ChatManager /></UserGuard>},
	{ path: "/chatmanager", element: <UserGuard><ChatManager /></UserGuard>},
	{ path: "/clientes", element: <UserGuard><Clientes /></UserGuard>},
	{ path: "/configuracion", element: <UserGuard><Configuracion /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/database-manager", element: <UserGuard><DatabaseManager /></UserGuard>},
	{ path: "/databasemanager", element: <UserGuard><DatabaseManager /></UserGuard>},
	{ path: "/integration-hub", element: <UserGuard><IntegrationHub /></UserGuard>},
	{ path: "/integrationhub", element: <UserGuard><IntegrationHub /></UserGuard>},
	{ path: "/inventory-manager", element: <UserGuard><InventoryManager /></UserGuard>},
	{ path: "/inventorymanager", element: <UserGuard><InventoryManager /></UserGuard>},
	{ path: "/nueva-renta", element: <UserGuard><NuevaRenta /></UserGuard>},
	{ path: "/nuevarenta", element: <UserGuard><NuevaRenta /></UserGuard>},
	{ path: "/rentas", element: <UserGuard><Rentas /></UserGuard>},
	{ path: "/reportes", element: <UserGuard><Reportes /></UserGuard>},
	{ path: "/shopify-manager", element: <UserGuard><ShopifyManager /></UserGuard>},
	{ path: "/shopifymanager", element: <UserGuard><ShopifyManager /></UserGuard>},
	{ path: "/stripe-manager", element: <UserGuard><StripeManager /></UserGuard>},
	{ path: "/stripemanager", element: <UserGuard><StripeManager /></UserGuard>},

];
